services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbnotes
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      
      
  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  postgres_data: